Rewrite pre-commit hook

diff --git a/Scripts/GitHooks/pre-commit b/Scripts/GitHooks/pre-commit
--- a/Scripts/GitHooks/pre-commit
+++ b/Scripts/GitHooks/pre-commit
@@ -9,28 +9,39 @@
 #LICENSE: MIT License
 
 branch=$(git rev-parse --abbrev-ref HEAD)
-if [ "$branch" == "stable" ]; then
-	echo "In general, you shouldn't commit directly to the stable branch!"
-	if ! make -j all > /dev/null; then
-		echo "To make matters worse, THIS COMMIT DOES NOT EVEN COMPILE!"
-		echo "UNDER NO CIRCUMSTANCES SHOULD YOU COMMIT THIS TO THE STABLE BRANCH!"
-		exit 1
+
+#0 = pass; 1 = soft fail; 2 = hard fail
+code=0
+
+if [ "$branch" == "stable" ] || [ "$branch" == "develop" ]; then
+	echo "Building..."
+	VALID_BUILD=$(make -j all > /dev/null; echo $?)
+	echo "Testing..."
+	VALID_TEST=$([ "$VALID_BUILD" = 0 ] && make -j test > /dev/null; echo $?)
+	if [ "$branch" == "stable" ]; then
+		code=1
+		echo "#In general, you shouldn't commit directly to the stable branch!"
+
+		if [ "$VALID_BUILD" != "0" ]; then
+			code=2
+			echo "#THIS COMMIT DOES NOT COMPILE!"
+			echo "UNDER NO CIRCUMSTANCES SHOULD YOU COMMIT THIS TO THE STABLE BRANCH!"
+		elif [ "$VALID_TEST" != "0" ]; then
+			echo "#This commit does not pass all tests!"
+		fi
+	elif [ "$branch" == "develop" ]; then
+		if [ "$VALID_BUILD" != "0" ]; then
+			code=2
+			echo "#THIS COMMIT DOES NOT COMPILE!"
+			echo "You *REALLY* shouldn't commit this to the develop branch!"
+		elif [ "$VALID_TEST" != "0" ]; then
+			code=1
+			echo "#This commit does not pass all tests!"
+			echo "Please fix them before committing to the develop branch!"
+		fi
 	fi
-	if ! make -j test > /dev/null; then
-		echo "To make matters worse, this commit does not even pass all tests!"
-	fi
+fi
+
+[ "$code" = "1" ] &&
 	echo "(To override this rejection, use \"git commit --no-verify\")"
-	exit 1
-fi
-if [ "$branch" == "develop" ]; then
-	if ! make -j all > /dev/null; then
-		echo "THIS COMMIT DOES NOT COMPILE!"
-		echo "You *REALLY* shouldn't commit this to the develop branch!"
-		exit 1
-	fi
-	if ! make -j test > /dev/null; then
-		echo "This commit does not pass all tests!"
-		echo "Please fix them before committing to the develop branch!"
-		echo "(To override this rejection, use \"git commit --no-verify\")"
-	fi
-fi
+exit $code
